# Generated by Django 5.1.2 on 2024-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
